package com.mic.smsgame.suquan;

import cg;

public class h
  extends cg
{
  public static final String[] a = { "Quả Cầu Lửa", "Mưa Thiên Thạch", "Lửa Địa Ngục", "Chuỗi Sét", "Khiên Sét", "Sấm Sét", "Mũi Tên Băng", "Cam Lộ Thủy", "Băng Phong" };
  public static final String[] b = { "Gây sát thương kẻ thù, lực sát thương bằng =, phá hủy tức thì 1 vùng diện tích 3x3ô trên bàn cờ.", "Gây sát thương kẻ thù, lực sát thương bằng =, phá hủy tức thì từ 3 đến 5 vùng diện tích 2x2ô trên bàn cờ.", "Gây sát thương kẻ thù, lực sát thương bằng =, phá hủy tức thì 2 vùng diện tích 4x4ô trên bàn cờ.", "Gây sát thương kẻ thù, lực sát thương bằng =, phá hủy tức thì từ 4 đến 8 ô trên bàn cờ.", "Hóa giải tất cả các đòn tấn công của kẻ thù. Tác dụng trong 6 lượt.", "Gây sát thương kẻ thù, lực sát thương bằng =, phá hủy tức thì từ 3 đến 6 vùng diện tích 3x3ô trên bàn cờ.", "Gây sát thương kẻ thù, lực sát thương bằng =, triệt tiêu một lượng nhỏ năng lượng của kẻ thù.", "Phục hồi 20% sinh lực cho bản thân. Phá hủy tất cả trái tim trên bàn cờ và hấp thụ sinh lực của trái tim bị hủy.", "Đóng băng kẻ thù trong 2 lượt, gây sát thương kẻ thù, lực sát thương bằng =, triệt tiêu một lượng lớn năng lượng của kẻ thù." };
  public static final String[] c = { "Long Thần Kiếm.", "Nhân Sâm.", "Ngân Lượng.", "Quỷ Diện Giáp.", "Bình Thuốc.", "Ngọc Ấn" };
  public static final String[] d = { "Nhân đôi sức mạnh tấn công trong một lượt.", "Nhân đôi lượng máu cơ bản của võ tướng. Chỉ sử dụng một lần trong một trận đánh.", "Nhận thêm được 1000 vàng.", "Ngăn cản 3/4 lực tấn công của kẻ thù trong một lượt", "Hồi phục ngay lập tức 10% sinh lực. Chỉ sử dụng một lần trong một lượt.", "Được ưu tiên đi trước nếu sở hữu ngọc ấn. Tự động kích hoạt khi bắt đầu trận đánh." };
  public static final String[] e = { "Một hào kiệt mang trong người sức mạnh hủy diệt của Lửa.", "Đại đệ tử của Lôi Thần, có khả năng điều khiển sấm sét để tấn công kẻ thù hoặc bảo vệ bản thân.", "Mang trong người dòng máu của Thủy Thần, có thể tự hồi phục tổn thương và đóng băng kẻ thù.", "Đệ tử của Hỏa Phụng Tiên, sở hữu sức mạnh hủy diệt của Lửa.", "Nữ hào kiệt xuất chúng, có quyền năng gọi sấm sét để tấn công kẻ thù hoặc tự bảo vệ bản thân.", "Hậu duệ của Bắc Hải Long Vương, có thể tự trị thương hoặc làm ngưng tụ hơi nước để đóng băng kẻ thù." };
  public static final String[][] f = { { "Loạn 12 sứ quân v1.0", "2010 MicroGame Corp." }, { "Thông tin và hỗ trợ", "Http://PhuThoBay.Pro" }, { "Kịch Bản Và Âm Thanh", "Nguyễn Tuấn Dũng" }, { "Lập Trình", "Lê Trung Trung", "Hồng Xuân Viên" }, { "Đồ Họa", "Nguyễn Duy Biểu", "Vũ Hà Thanh" }, { "Kiểm Định", "Nguyễn Văn Quang" } };
  public static final String[] g = { "Kính Bát Quái", "Khánh Kim Long", "Ngọc Bội", "Tượng Phật" };
  public static final String[] h = { "Năm 944,", "Ngô Quyền mất", "Em vợ là", "Dương Tam Kha", "cướp ngôi", "tự lập mình làm vua,", "xưng Dương Bình Vương.", " ", "Từ khi Dương Tam Kha", "lấy ngôi nhà Ngô", "thủ lĩnh các nơi", "không chịu thuần phục,", "đua nhau nổi dậy", "chiếm cứ quận ấp.", "Đất nước loạn lạc...", " ", "Năm 950,", "Dương Bình Vương sai", "con thứ của Ngô Quyền", "là Ngô Xương Văn", "đi đánh Thái Bình.", "Ngô Xương Văn", "dẫn quân quay lại", "lật đổ Dương Tam Kha", "và lên ngôi vua,", "xưng là Nam Tấn Vương.", " ", "Năm 954,", "Ngô Xương Văn", "đi thảo phạt chư thần", "bị phục binh bắn chết.", " ", "Cháu của Xương Văn", "là Ngô Xương Xí", "nối nghiệp, nhưng", "thế lực ngày càng yếu ", "phải rút quân về giữ ", "đất Bình Kiều.", " ", "Năm 966,", "hình thành đầy đủ", "12 sứ quân", "chiếm giữ các", "địa phương:", " ", "1.Ngô Xương Xí", "chiếm Bình Kiều", " ", "2.Đỗ Cảnh Thạc", "chiếm Đỗ Động Giang", " ", "3.Trần Lãm", "giữ Bố Hải Khẩu", " ", "4.Kiều Công Hãn ", "giữ Phong Châu", " ", "5.Nguyễn Khoan", "chiếm Tam Đái", " ", "6.Ngô Nhật Khánh", "giữ Đường Lâm", " ", "7.Lý Khuê", "chiếm Siêu Loại", " ", "8.Nguyễn Thủ Tiệp", "giữ Tiên Du", " ", "9.Lã Đường", "chiếm Tế Giang", " ", "10.Nguyễn Siêu", "giữ Tây Phù Liệt", " ", "11.Kiều Thuận", "chiếm Hồi Hồ", " ", "12.Phạm Bạch Hổ", "giữ Đằng Châu", " ", "Cùng thời gian này,", "Đinh Bộ Lĩnh", "nổi dậy", "tập hợp dân chúng", "ở vùng Hoa Lư", "chờ thời cơ.", " ", "Để mở rộng căn cứ", "Đinh Bộ Lĩnh", "sang đầu quân", "cho Trần Lãm", "và được Trần Lãm", "gả con gái cho.", " ", "Sau đó,", "ông được Trần Lãm", "trao binh quyền và", "đưa quân về Hoa Lư,", "chiêu mộ tướng tài", "chống nhà Ngô", "và các sứ quân khác.", " ", "Hào Kiệt khắp nơi", "tụ về phò giúp,", "ngày ngày tập trận", "chờ cơ hội xuất quân", "......." };
  public static final String[] i = { "Năm 968,", "sau khi", "dẹp loạn 12 sứ quân.", " ", "Đinh Bộ Lĩnh", "lên ngôi Hoàng Đế,", "xưng là", "Đại Thắng Minh", "Hoàng Đế,", "tức Đinh Tiên Hoàng,", "đóng đô ở Hoa Lư.", " ", "Năm 971,", "Đinh Tiên Hoàng", "bắt đầu quy định", "cấp bậc văn võ", "trong triều đình.", " ", "Trong triều", "có sự tham gia", "của các nhà sư", "vì những đóng góp", "trong quá trình", "dẹp loạn 12 sứ quân.", " ", "Đinh Tiên Hoàng", "phong cho", "các quan văn võ:", " ", "- Nguyễn Bặc làm", " Định quốc công", " ", "- Lưu Cơ làm", "Đô hộ phủ sĩ sư", " ", "- Lê Hoàn làm", "Thập đạo tướng quân", " ", "- Ngô Chân Lưu làm", "Khuông việt đại sư", " ", "- Phạm Bạch Hổ làm", "Thân vệ đại tướng quân ", "- Phạm Cự Lạng làm", "Phòng ngự sứ tướng quân ", "- Bùi Quang Dũng làm", "Trấn đông tiết độ sứ- {s} làm ", "......" };
}


/* Location:           C:\Users\CapVanVu\Downloads\loan-12-su-quan.jar
 * Qualified Name:     com.mic.smsgame.suquan.h
 * JD-Core Version:    0.7.0.1
 */